packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - esbuild
  - protobufjs
allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: false

overrides:
  "@opentelemetry/propagator-jaeger": ">=2.9.0"
