import { fileURLToPath } from "node:url";
import { defineConfig, devices } from "@playwright/test";

/**
 * Browser-level coverage: the layer neither the node render harness nor the unit
 * suites can reach.
 *
 * What runs here, and why it has to be a browser:
 *
 *   - **`admin.spec.ts`** drives the real admin console — `next dev` rendering
 *     real server components against a stubbed upstream API — and asserts the
 *     claims that only survive if the markup, the stylesheet and the browser all
 *     agree. A status carries its tone as `data-tone` precisely because CSS
 *     cannot match on text; whether that attribute actually produces four
 *     distinguishable colours is a question only `getComputedStyle` answers.
 *   - **`gallery.spec.ts`** drives `/gallery`, which renders every shared
 *     primitive against the real stylesheets. It is where "a failed read does not
 *     look like an empty one" stops being a claim about class names.
 *   - **`gallery-visual.spec.ts`** takes pixel snapshots of the same specimens.
 *     It is opt-in — see the determinism note below.
 *
 * No credentials are involved. Admin's inbound gate permits an unauthenticated
 * request only when `NODE_ENV !== "production"`, which Next inlines at build
 * time and compiles out of every deployed image; `next dev` is exactly that
 * case. Nothing here weakens the gate, and nothing here is a new bypass.
 *
 * ## Determinism, and what is deliberately not committed
 *
 * Everything under this directory is pinned: one viewport, one locale, one
 * timezone, one colour profile, transitions and animations zeroed, the caret
 * hidden, Next's dev overlay hidden, and `Date.now()` fixed (see
 * `support/harness.ts`).
 *
 * That is enough to make *behaviour* reproducible on any machine, and the
 * functional projects below gate CI on it.
 *
 * It is not enough to make *pixels* reproducible. Text rasterisation differs
 * between macOS CoreText and Linux FreeType for the same font at the same size,
 * and overlay scrollbars differ again. A baseline captured on a developer's Mac
 * fails on every Linux runner, forever; a baseline captured only in CI cannot be
 * regenerated by the developer who needs to change it. Both roads end at a
 * suite people learn to ignore.
 *
 * So pixel baselines are **not committed and do not gate CI**. The snapshot
 * project exists, fully configured, and is opt-in:
 *
 *     pnpm test:e2e:visual:update    # capture baselines for this machine
 *     pnpm test:e2e:visual           # compare against them
 *
 * That is a before/after check for whoever is changing a component — capture,
 * edit, compare — and it is genuinely useful for that. It is not a shared
 * artifact, and `snapshotPathTemplate` writes under
 * `e2e/__screenshots__/<platform>/…` so it can never be mistaken for one. The
 * directory is git-ignored.
 *
 * If this repo later decides gating visual regression is worth the maintenance,
 * the shape is already here and the change is additive: generate baselines
 * inside `mcr.microsoft.com/playwright:v<version>-noble` — the image the CI
 * runner matches, with a repo copy of its own, because a bind mount would have
 * `pnpm install` overwrite the host's native binaries with Linux ones — commit
 * only what that image produced, and add the `visual` project to the `browser`
 * job in ci.yml. Nothing about the config or the specs has to change.
 *
 * What *does* gate CI is the deterministic half of the same idea: computed
 * colours, resolved pseudo-element content, grid track counts, and focus order,
 * all asserted from a real engine. Chromium computes those identically on every
 * platform; only their rasterisation differs. They catch the failures this repo
 * has actually shipped — a stylesheet that stopped matching its markup — without
 * ever failing for a reason nobody can act on.
 */

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));

const STUB_PORT = Number(process.env.STUB_API_PORT ?? 4310);
/** Deliberately not admin's own 3100, so a running `pnpm dev` is not disturbed. */
const ADMIN_PORT = Number(process.env.ADMIN_E2E_PORT ?? 3210);
/**
 * `localhost`, not `127.0.0.1`. Next 16 refuses cross-origin requests for its
 * own development resources, and it considers the two different origins: driving
 * the app on the loopback address blocks the HMR channel, the client bundle
 * never finishes booting, and the page never hydrates. Every interactive
 * assertion then fails for a reason that has nothing to do with the product.
 */
const ADMIN_URL = `http://localhost:${ADMIN_PORT}`;

const VISUAL = process.env.PLAYWRIGHT_VISUAL === "1";

const chromium = {
  ...devices["Desktop Chrome"],
  // Fixed viewport above both stylesheets' breakpoints (1100px, 700px), so the
  // default run is the desktop layout and a test that wants another one has to
  // resize on purpose.
  viewport: { width: 1280, height: 800 },
  deviceScaleFactor: 1,
  colorScheme: "dark" as const,
  reducedMotion: "reduce" as const,
  locale: "en-US",
  timezoneId: "UTC",
  launchOptions: {
    args: [
      // Rasterisation controls. They do not make macOS and Linux agree — nothing
      // does — but they remove the variance *within* a platform, which is what
      // makes a locally generated baseline usable locally.
      "--force-color-profile=srgb",
      "--font-render-hinting=none",
      "--disable-lcd-text"
    ]
  }
};

export default defineConfig({
  testDir: fileURLToPath(new URL(".", import.meta.url)),
  outputDir: fileURLToPath(new URL("./.artifacts", import.meta.url)),
  snapshotPathTemplate: "{testDir}/__screenshots__/{platform}/{testFileName}/{arg}{ext}",

  // Tests within a file stay in order. The admin suite switches scenario on a
  // single shared stub process, which is server state, so its file must not be
  // split across workers.
  fullyParallel: false,
  workers: 1,
  forbidOnly: Boolean(process.env.CI),
  retries: 0,
  reporter: process.env.CI ? [["github"], ["list"]] : [["list"]],

  use: {
    ...chromium,
    baseURL: ADMIN_URL,
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "off"
  },

  expect: {
    timeout: 10_000,
    toHaveScreenshot: {
      animations: "disabled",
      caret: "hide",
      // CSS pixels rather than device pixels, so a HiDPI machine and a CI runner
      // capture the same grid.
      scale: "css",
      maxDiffPixelRatio: 0.005
    }
  },

  // `next dev` compiles on first request; the first navigation in a cold run is
  // measured in seconds, not milliseconds.
  timeout: 90_000,

  projects: [
    { name: "admin", testMatch: /admin\.spec\.ts$/, use: chromium },
    { name: "gallery", testMatch: /gallery\.spec\.ts$/, use: chromium },
    ...(VISUAL ? [{ name: "visual", testMatch: /gallery-visual\.spec\.ts$/, use: chromium }] : [])
  ],

  webServer: [
    {
      command: "node --experimental-strip-types e2e/support/stub-api.ts",
      cwd: REPO_ROOT,
      url: `http://127.0.0.1:${STUB_PORT}/__health`,
      env: { STUB_API_PORT: String(STUB_PORT) },
      reuseExistingServer: !process.env.CI,
      stdout: "pipe",
      stderr: "pipe"
    },
    {
      command: `pnpm --filter @jina/admin exec next dev --port ${ADMIN_PORT}`,
      cwd: REPO_ROOT,
      // `/gallery` renders no API data, so readiness cannot be confused with the
      // stub being up or with any particular scenario.
      url: `${ADMIN_URL}/gallery`,
      env: {
        JINA_API_URL: `http://127.0.0.1:${STUB_PORT}`,
        // Pinned empty so a developer's shell cannot change what these tests
        // exercise: a stray INTERNAL_API_TOKEN without a principal makes
        // `adminApiHeaders` throw, and stray web credentials would turn every
        // navigation into a 401.
        INTERNAL_API_TOKEN: "",
        JINA_TENANT_ID: "",
        JINA_WEB_PRINCIPAL_ID: "",
        JINA_WEB_AUTH_USERNAME: "",
        JINA_WEB_AUTH_PASSWORD: ""
      },
      reuseExistingServer: !process.env.CI,
      timeout: 180_000,
      stdout: "pipe",
      stderr: "pipe"
    }
  ]
});
