#!/usr/bin/env bash
# Restart only the API and Board workers of an existing local stack.
#
# PostgreSQL, api_state, immutable artifacts, generated credentials, PageIndex,
# and prior logs are preserved. Use --build explicitly to compile the current
# checkout before the process restart.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/dev-process-lib.sh
source "$REPO/scripts/dev-process-lib.sh"

dev_restart_main() {
  local rebuild=false
  local capture_current=false
  local reseed_local_state=false
  while (($# > 0)); do
    case "$1" in
      --build) rebuild=true; shift ;;
      --capture-current) capture_current=true; shift ;;
      --reseed-local-state) reseed_local_state=true; shift ;;
      -h|--help)
        echo "usage: scripts/dev-restart.sh [--build]"
        echo "       --build compiles and migrates retained PostgreSQL before restart"
        echo "       scripts/dev-restart.sh --capture-current"
        echo "       scripts/dev-restart.sh --reseed-local-state"
        return 0
        ;;
      *)
        echo "unknown option: $1" >&2
        return 2
        ;;
    esac
  done

  local state_directory="${JINA_DEV_STATE_DIR:-/tmp/jina-dev}"
  local restart_file="${JINA_DEV_RESTART_FILE:-$state_directory/restart.env}"
  jina_validate_safe_directory JINA_DEV_STATE_DIR "$state_directory"
  if [[ "$reseed_local_state" == true ]]; then
    [[ "$rebuild" == false && "$capture_current" == false ]] || {
      echo "--reseed-local-state cannot be combined with another action" >&2
      return 2
    }
    reseed_local_restart_state "$state_directory" "$restart_file"
    return
  fi
  if [[ "$capture_current" == true ]]; then
    [[ "$rebuild" == false ]] || {
      echo "--capture-current and --build cannot be combined" >&2
      return 2
    }
    capture_current_restart_state "$state_directory" "$restart_file"
    return
  fi
  if [[ ! -f "$restart_file" || -L "$restart_file" ]]; then
    echo "No trusted restart state at $restart_file; run scripts/dev-up.sh first." >&2
    return 1
  fi
  assert_private_owned_file "$restart_file"
  # Generated by dev-up with mode 600 and shell-escaped values.
  # shellcheck disable=SC1090
  source "$restart_file"
  restart_required JINA_RESTART_TENANT
  resolve_context_query_principal_restart_metadata
  local context_query_principal_changed=false requested_context_query_principal
  if [[ -n "${JINA_DEV_CONTEXT_QUERY_PRINCIPAL_ID:-}" ]]; then
    requested_context_query_principal="$(
      jina_resolve_local_context_query_principal \
        "$JINA_RESTART_TENANT" \
        "$JINA_DEV_CONTEXT_QUERY_PRINCIPAL_ID" \
        JINA_DEV_CONTEXT_QUERY_PRINCIPAL_ID
    )"
    if [[ "$requested_context_query_principal" != "$JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID" ]]; then
      JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID="$requested_context_query_principal"
      context_query_principal_changed=true
    fi
  fi
  restart_required \
    JINA_RESTART_REPO JINA_RESTART_CONTAINER JINA_RESTART_ENV_FILE \
    JINA_RESTART_DATABASE_URL JINA_RESTART_API_PORT JINA_RESTART_WORKER_PORT_BASE \
    JINA_RESTART_PGPORT JINA_RESTART_TENANT JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID \
    JINA_RESTART_INTERNAL_TOKEN \
    JINA_RESTART_CONTEXT_TOKEN JINA_RESTART_ARTIFACT_DIR \
    JINA_RESTART_PAGEINDEX_SOURCE_ROOT JINA_RESTART_PAGEINDEX_PYTHON \
    JINA_RESTART_PAGEINDEX_WORKER JINA_RESTART_CODEX_HOME JINA_RESTART_CODEX_BINARY \
    JINA_RESTART_MODEL JINA_RESTART_EFFORT JINA_RESTART_CONTEXT_TOKENS \
    JINA_RESTART_COMPACT_TOKENS JINA_RESTART_AGENT_WORKERS \
    JINA_RESTART_AUDIT_WORKERS JINA_RESTART_LOG_RETENTION
  if [[ "$rebuild" == true ]]; then
    resolve_migration_restart_metadata
    restart_required JINA_RESTART_MIGRATION_DATABASE_URL JINA_RESTART_RUNTIME_DB_USER
    [[ "$JINA_RESTART_RUNTIME_DB_USER" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || {
      echo "Restart state contains an invalid runtime database role." >&2
      return 1
    }
    assert_retained_database_targets \
      "$JINA_RESTART_DATABASE_URL" \
      "$JINA_RESTART_MIGRATION_DATABASE_URL" \
      "$JINA_RESTART_PGPORT" \
      "$JINA_RESTART_RUNTIME_DB_USER"
  fi

  if [[ "$JINA_RESTART_REPO" != "$REPO" ]]; then
    echo "Restart state belongs to $JINA_RESTART_REPO, not this checkout." >&2
    return 1
  fi
  local environment_file="$JINA_RESTART_ENV_FILE"
  if [[ ! -f "$environment_file" || -L "$environment_file" ]]; then
    echo "Generated environment file is missing or untrusted: $environment_file" >&2
    return 1
  fi
  assert_private_owned_file "$environment_file"
  jina_validate_safe_directory JINA_RESTART_ARTIFACT_DIR "$JINA_RESTART_ARTIFACT_DIR"
  for value in \
    "$JINA_RESTART_API_PORT" "$JINA_RESTART_WORKER_PORT_BASE" \
    "$JINA_RESTART_AGENT_WORKERS" "$JINA_RESTART_AUDIT_WORKERS" \
    "$JINA_RESTART_LOG_RETENTION" "$JINA_RESTART_CONTEXT_TOKENS" \
    "$JINA_RESTART_COMPACT_TOKENS"; do
    [[ "$value" =~ ^[1-9][0-9]*$ ]] || {
      echo "Restart state contains an invalid positive integer." >&2
      return 1
    }
  done
  for tool in curl docker node pnpm python3; do
    command -v "$tool" >/dev/null || {
      echo "$tool is required" >&2
      return 2
    }
  done
  [[ -x "$JINA_RESTART_CODEX_BINARY" ]] || {
    echo "Codex binary is no longer executable: $JINA_RESTART_CODEX_BINARY" >&2
    return 1
  }
  [[ -f "$JINA_RESTART_CODEX_HOME/auth.json" ]] || {
    echo "The preserved Codex session is unavailable; run codex login." >&2
    return 1
  }
  [[ -d "$JINA_RESTART_ARTIFACT_DIR" ]] || {
    echo "Immutable artifact directory disappeared: $JINA_RESTART_ARTIFACT_DIR" >&2
    return 1
  }

  local owner running container_id_before
  owner="$(docker inspect -f '{{ index .Config.Labels "com.jina.local-context.repo" }}' \
    "$JINA_RESTART_CONTAINER" 2>/dev/null || true)"
  running="$(docker inspect -f '{{.State.Running}}' "$JINA_RESTART_CONTAINER" 2>/dev/null || true)"
  container_id_before="$(docker inspect -f '{{.Id}}' "$JINA_RESTART_CONTAINER" 2>/dev/null || true)"
  if [[ "$owner" != "$REPO" || "$running" != "true" || -z "$container_id_before" ]]; then
    echo "Owned running PostgreSQL container $JINA_RESTART_CONTAINER is required." >&2
    return 1
  fi

  PAGEINDEX_SOURCE_ROOT="$JINA_RESTART_PAGEINDEX_SOURCE_ROOT" \
    "$JINA_RESTART_PAGEINDEX_PYTHON" "$JINA_RESTART_PAGEINDEX_WORKER" --probe >/dev/null

  if [[ "$rebuild" == true ]]; then
    echo "==> explicit workspace rebuild"
    (cd "$REPO" && pnpm build --force >/dev/null)
  fi

  local environment_digest_before restart_digest_before builds_before=""
  environment_digest_before="$(file_digest "$environment_file")"
  restart_digest_before="$(file_digest "$restart_file")"
  builds_before="$(context_builds_json 2>/dev/null || true)"

  echo "==> stopping recorded API/worker processes (PostgreSQL remains running)"
  jina_stop_recorded_processes "$REPO" "$state_directory" 120

  local role
  local -a roles=(snapshot)
  local index
  for index in $(seq 1 "$JINA_RESTART_AGENT_WORKERS"); do roles+=("agent-$index"); done
  for index in $(seq 1 "$JINA_RESTART_AUDIT_WORKERS"); do roles+=("auditor-$index"); done
  roles+=(certification publication pageindex)
  jina_rotate_log "$state_directory" "$JINA_RESTART_LOG_RETENTION" api
  for role in "${roles[@]}"; do
    jina_rotate_log "$state_directory" "$JINA_RESTART_LOG_RETENTION" "worker-$role"
  done

  local restart_complete=false
  cleanup_failed_restart() {
    local status="$1"
    if [[ "$restart_complete" != true ]]; then
      jina_stop_recorded_processes "$REPO" "$state_directory" 120 >/dev/null 2>&1 || true
      echo "Process restart failed. PostgreSQL, Board state, artifacts, tokens, and logs remain intact." >&2
    fi
    return "$status"
  }
  trap 'cleanup_failed_restart "$?"' ERR

  if [[ "$rebuild" == true ]]; then
    echo "==> applying current PostgreSQL schema and runtime grants"
    DATABASE_URL="$JINA_RESTART_MIGRATION_DATABASE_URL" \
      CONTEXT_RUNTIME_DB_USER="$JINA_RESTART_RUNTIME_DB_USER" \
      node "$REPO/packages/db/dist/migrate.js" --install-roles >/dev/null
  fi

  echo "==> API on :$JINA_RESTART_API_PORT"
  (
    export DATABASE_URL="$JINA_RESTART_DATABASE_URL"
    export INTERNAL_API_TOKEN="$JINA_RESTART_INTERNAL_TOKEN"
    export CONTEXT_API_TOKEN="$JINA_RESTART_CONTEXT_TOKEN"
    # shellcheck disable=SC2030 # This API subprocess receives the stored tenant.
    export JINA_TENANT_ID="$JINA_RESTART_TENANT"
    export JINA_CONTEXT_TENANT_ID="$JINA_RESTART_TENANT"
    export JINA_CONTEXT_PRINCIPAL_ID="$JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID"
    export JINA_TENANT_ADMIN_PRINCIPALS="tenant:$JINA_RESTART_TENANT"
    export JINA_DB_MANAGE_SCHEMA=false
    export JINA_ENABLE_DEV_ENDPOINTS=true
    export JINA_TRUST_DEV_IDENTITY_HEADERS=false
    # shellcheck disable=SC2030 # This API subprocess receives the stored artifact path.
    export CONTEXT_ARTIFACT_DIRECTORY="$JINA_RESTART_ARTIFACT_DIR"
    # shellcheck disable=SC2030 # The API subprocess receives its own port.
    export PORT="$JINA_RESTART_API_PORT"
    jina_spawn_detached "$state_directory/api.log" node "$REPO/apps/api/dist/dev-server.js"
  ) >"$state_directory/api.pid"
  if ! jina_wait_for_health "http://127.0.0.1:$JINA_RESTART_API_PORT/health" 60 1; then
    echo "API restart failed; see $state_directory/api.log" >&2
    tail -30 "$state_directory/api.log" >&2 || true
    return 1
  fi

  local -a worker_common=(
    "JINA_API_URL=http://127.0.0.1:$JINA_RESTART_API_PORT"
    "INTERNAL_API_TOKEN=$JINA_RESTART_INTERNAL_TOKEN"
    "JINA_REQUIRE_GITHUB_INSTALLATION=false"
    "GIT_TERMINAL_PROMPT=0"
    "GITHUB_API_TOKEN=${JINA_RESTART_GITHUB_TOKEN:-}"
    "GITHUB_CLONE_TOKEN=${JINA_RESTART_GITHUB_TOKEN:-}"
    "CONTEXT_BOARD_EXECUTOR=local"
    "CONTEXT_CODEX_AUTH=session"
    "CONTEXT_CODEX_MODEL=$JINA_RESTART_MODEL"
    "CONTEXT_CODEX_EFFORT=$JINA_RESTART_EFFORT"
    "CONTEXT_CODEX_VERBOSITY=high"
    "CONTEXT_CODEX_CONTEXT_TOKENS=$JINA_RESTART_CONTEXT_TOKENS"
    "CONTEXT_CODEX_COMPACT_TOKENS=$JINA_RESTART_COMPACT_TOKENS"
    "CONTEXT_AGENT_ARCHIVE_MAX_BYTES=134217728"
    "CONTEXT_API_TIMEOUT_MS=7200000"
    "CONTEXT_DERIVE_BUDGET_SECONDS=5400"
    "CONTEXT_PAGEINDEX_PROCESS_TIMEOUT_MS=300000"
    "CONTEXT_PAGEINDEX_BUILD_TIMEOUT_MS=300000"
    "CONTEXT_PAGEINDEX_PYTHON=$JINA_RESTART_PAGEINDEX_PYTHON"
    "CONTEXT_PAGEINDEX_WORKER=$JINA_RESTART_PAGEINDEX_WORKER"
    "PAGEINDEX_SOURCE_ROOT=$JINA_RESTART_PAGEINDEX_SOURCE_ROOT"
    "CODEX_BINARY=$JINA_RESTART_CODEX_BINARY"
    "CODEX_HOME=$JINA_RESTART_CODEX_HOME"
    "NODE_ENV=development"
  )
  local worker_index=0
  local -a worker_roles=() worker_topics=() worker_ports=()

  restart_worker() {
    local worker_role="$1" topics="$2" port
    port=$((JINA_RESTART_WORKER_PORT_BASE + worker_index))
    worker_index=$((worker_index + 1))
    worker_roles+=("$worker_role")
    worker_topics+=("$topics")
    worker_ports+=("$port")
    (
      export "${worker_common[@]}"
      export WORKER_ID="dev-$worker_role"
      export WORKER_TOPICS="$topics"
      # shellcheck disable=SC2031 # Each worker subprocess receives a distinct port.
      export PORT="$port"
      jina_spawn_detached "$state_directory/worker-$worker_role.log" \
        node "$REPO/apps/worker/dist/server.js"
    ) >"$state_directory/worker-$worker_role.pid"
  }

  echo "==> Board workers"
  restart_worker snapshot "run-context-input-snapshot"
  for index in $(seq 1 "$JINA_RESTART_AGENT_WORKERS"); do
    restart_worker "agent-$index" \
      "run-context-page-plan|run-context-page-build"
  done
  for index in $(seq 1 "$JINA_RESTART_AUDIT_WORKERS"); do
    restart_worker "auditor-$index" \
      "run-context-page-build"
  done
  restart_worker certification "run-context-page-plan"
  restart_worker publication "run-context-publication"
  restart_worker pageindex "run-context-publication"

  for index in "${!worker_roles[@]}"; do
    if ! jina_wait_for_health "http://127.0.0.1:${worker_ports[$index]}/health" 90 1; then
      echo "Worker ${worker_roles[$index]} restart failed; see $state_directory/worker-${worker_roles[$index]}.log" >&2
      return 1
    fi
    verify_worker_topology \
      "http://127.0.0.1:${worker_ports[$index]}/health" \
      "dev-${worker_roles[$index]}" \
      "${worker_topics[$index]}"
  done

  local container_id_after running_after
  container_id_after="$(docker inspect -f '{{.Id}}' "$JINA_RESTART_CONTAINER")"
  running_after="$(docker inspect -f '{{.State.Running}}' "$JINA_RESTART_CONTAINER")"
  [[ "$container_id_after" == "$container_id_before" && "$running_after" == "true" ]] || {
    echo "PostgreSQL container identity changed during process-only restart." >&2
    return 1
  }
  if [[ "$context_query_principal_changed" == true ]]; then
    update_shell_export_file \
      "$environment_file" JINA_CONTEXT_PRINCIPAL_ID "$JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID"
    update_shell_export_file \
      "$restart_file" JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID "$JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID"
    environment_digest_before="$(file_digest "$environment_file")"
    restart_digest_before="$(file_digest "$restart_file")"
  fi
  [[ "$(file_digest "$environment_file")" == "$environment_digest_before" ]] || {
    echo "Generated environment/tokens changed during restart." >&2
    return 1
  }
  [[ "$(file_digest "$restart_file")" == "$restart_digest_before" ]] || {
    echo "Private restart configuration changed during restart." >&2
    return 1
  }

  local builds_after
  builds_after="$(context_builds_json)"
  assert_builds_preserved "$builds_before" "$builds_after"
  print_build_observability "$builds_after" "$JINA_RESTART_API_PORT"

  restart_complete=true
  trap - ERR
  echo
  echo "Process-only restart complete:"
  echo "  PostgreSQL: $JINA_RESTART_CONTAINER ($container_id_after), preserved"
  echo "  Board state: PostgreSQL jina_runtime.api_state, preserved"
  echo "  Artifacts:   $JINA_RESTART_ARTIFACT_DIR, preserved"
  if [[ "$context_query_principal_changed" == true ]]; then
    echo "  Tokens/env:  credentials unchanged; Context query principal retained in $environment_file"
  else
    echo "  Tokens/env:  $environment_file, unchanged"
  fi
  echo "  Workers:     ${worker_roles[*]}"
}

reseed_local_restart_state() {
  local state_directory="$1" restart_file="$2"
  local environment_file="${JINA_DEV_ENV_FILE:-/tmp/jina-dev.env}"
  local container="${JINA_DEV_CONTAINER:-jina-dev-postgres}"
  local database="${JINA_DEV_DATABASE:-jina_dev}"
  local pg_port="${JINA_DEV_PGPORT:-55480}"
  local api_port="${JINA_DEV_API_PORT:-4180}"
  local worker_port_base="${JINA_DEV_WORKER_PORT_BASE:-8091}"
  local tenant="${JINA_DEV_TENANT_ID:-11111111-1111-4111-8111-111111111111}"
  local context_query_principal
  context_query_principal="$(
    jina_resolve_local_context_query_principal \
      "$tenant" "${JINA_DEV_CONTEXT_QUERY_PRINCIPAL_ID:-}" JINA_DEV_CONTEXT_QUERY_PRINCIPAL_ID
  )"
  local artifact_directory="${JINA_DEV_ARTIFACT_DIRECTORY:-$state_directory/artifacts}"
  local pageindex_pin_short="982514ab40fe"
  local pageindex_source="${PAGEINDEX_SOURCE_ROOT:-$state_directory/pageindex/PageIndex-$pageindex_pin_short}"
  local pageindex_python="${CONTEXT_PAGEINDEX_PYTHON:-$state_directory/pageindex/venv/bin/python}"
  local pageindex_worker="${CONTEXT_PAGEINDEX_WORKER:-$REPO/services/pageindex-worker/worker.py}"
  local codex_session_home_path="${CODEX_HOME:-$HOME/.codex}"
  local codex_home_path="${JINA_DEV_CODEX_RUNTIME_HOME:-$state_directory/codex-home}"
  local codex_binary_path="${CODEX_BINARY:-$(command -v codex 2>/dev/null || true)}"
  local model="${JINA_DEV_CODEX_MODEL:-gpt-5.6-terra}"
  local effort="${JINA_DEV_CODEX_EFFORT:-low}"
  local context_tokens="${JINA_DEV_CODEX_CONTEXT_TOKENS:-128000}"
  local compact_tokens="${JINA_DEV_CODEX_COMPACT_TOKENS:-96000}"
  local agent_workers="${JINA_DEV_AGENT_WORKERS:-3}"
  local audit_workers="${JINA_DEV_AUDIT_WORKERS:-2}"
  local log_retention="${JINA_DEV_LOG_RETENTION:-5}"
  local runtime_user="${JINA_DEV_RUNTIME_USER:-jina_runtime}"
  local runtime_password="${JINA_DEV_RUNTIME_PASSWORD:-dev-runtime}"
  local migration_user="${JINA_DEV_MIGRATION_USER:-jina_app}"
  local migration_password="${JINA_DEV_MIGRATION_PASSWORD:-dev-migration}"

  [[ ! -e "$environment_file" && ! -e "$restart_file" ]] || {
    echo "Refusing to overwrite existing local environment or restart state." >&2
    return 1
  }
  jina_validate_safe_directory JINA_DEV_ARTIFACT_DIRECTORY "$artifact_directory"
  local owner running retained_rows
  owner="$(docker inspect -f '{{ index .Config.Labels "com.jina.local-context.repo" }}' "$container" 2>/dev/null || true)"
  running="$(docker inspect -f '{{.State.Running}}' "$container" 2>/dev/null || true)"
  [[ "$owner" == "$REPO" && "$running" == "true" ]] || {
    echo "An owned running PostgreSQL container is required before reseeding local process state." >&2
    return 1
  }
  retained_rows="$(
    docker exec "$container" psql -U postgres -d "$database" -Atc \
      "select count(*) from jina_runtime.api_state" 2>/dev/null || true
  )"
  [[ "$retained_rows" =~ ^[1-9][0-9]*$ ]] || {
    echo "The attached PostgreSQL database does not contain retained Board state." >&2
    return 1
  }
  [[ -d "$artifact_directory" && -x "$pageindex_python" && -f "$pageindex_worker" ]] || {
    echo "Retained artifacts or the pinned PageIndex runtime are unavailable." >&2
    return 1
  }
  [[ -n "$codex_binary_path" && -x "$codex_binary_path" && -f "$codex_session_home_path/auth.json" ]] || {
    echo "The current Codex binary/session is unavailable." >&2
    return 1
  }
  jina_prepare_codex_runtime_home "$codex_session_home_path" "$codex_home_path"
  PAGEINDEX_SOURCE_ROOT="$pageindex_source" "$pageindex_python" "$pageindex_worker" --probe >/dev/null

  local internal_token context_token github_token runtime_url migration_url
  internal_token="$(openssl rand -hex 32)"
  context_token="$(openssl rand -hex 32)"
  github_token="${GITHUB_API_TOKEN:-${GITHUB_CLONE_TOKEN:-}}"
  if [[ -z "$github_token" ]] && command -v gh >/dev/null; then
    github_token="$(gh auth token 2>/dev/null || true)"
  fi
  runtime_url="postgres://$runtime_user:$runtime_password@127.0.0.1:$pg_port/$database"
  migration_url="postgres://$migration_user:$migration_password@127.0.0.1:$pg_port/$database"

  umask 077
  {
    echo "# Recreated by scripts/dev-restart.sh after attaching retained PostgreSQL state."
    printf 'export JINA_API_URL=%q\n' "http://127.0.0.1:$api_port"
    printf 'export JINA_INTERNAL_TOKEN=%q\n' "$internal_token"
    printf 'export JINA_CONTEXT_TOKEN=%q\n' "$context_token"
    printf 'export JINA_TENANT_ID=%q\n' "$tenant"
    printf 'export JINA_CONTEXT_PRINCIPAL_ID=%q\n' "$context_query_principal"
    printf 'export JINA_DEV_STATE_DIR=%q\n' "$state_directory"
    printf 'export CONTEXT_ARTIFACT_DIRECTORY=%q\n' "$artifact_directory"
    printf 'export PAGEINDEX_SOURCE_ROOT=%q\n' "$pageindex_source"
    printf 'export CONTEXT_PAGEINDEX_PYTHON=%q\n' "$pageindex_python"
    printf 'export CONTEXT_PAGEINDEX_WORKER=%q\n' "$pageindex_worker"
  } >"$environment_file"
  {
    printf 'export JINA_RESTART_REPO=%q\n' "$REPO"
    printf 'export JINA_RESTART_CONTAINER=%q\n' "$container"
    printf 'export JINA_RESTART_ENV_FILE=%q\n' "$environment_file"
    printf 'export JINA_RESTART_DATABASE_URL=%q\n' "$runtime_url"
    printf 'export JINA_RESTART_MIGRATION_DATABASE_URL=%q\n' "$migration_url"
    printf 'export JINA_RESTART_RUNTIME_DB_USER=%q\n' "$runtime_user"
    printf 'export JINA_RESTART_API_PORT=%q\n' "$api_port"
    printf 'export JINA_RESTART_WORKER_PORT_BASE=%q\n' "$worker_port_base"
    printf 'export JINA_RESTART_PGPORT=%q\n' "$pg_port"
    printf 'export JINA_RESTART_TENANT=%q\n' "$tenant"
    printf 'export JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID=%q\n' "$context_query_principal"
    printf 'export JINA_RESTART_INTERNAL_TOKEN=%q\n' "$internal_token"
    printf 'export JINA_RESTART_CONTEXT_TOKEN=%q\n' "$context_token"
    printf 'export JINA_RESTART_ARTIFACT_DIR=%q\n' "$artifact_directory"
    printf 'export JINA_RESTART_PAGEINDEX_SOURCE_ROOT=%q\n' "$pageindex_source"
    printf 'export JINA_RESTART_PAGEINDEX_PYTHON=%q\n' "$pageindex_python"
    printf 'export JINA_RESTART_PAGEINDEX_WORKER=%q\n' "$pageindex_worker"
    printf 'export JINA_RESTART_CODEX_HOME=%q\n' "$codex_home_path"
    printf 'export JINA_RESTART_CODEX_BINARY=%q\n' "$codex_binary_path"
    printf 'export JINA_RESTART_MODEL=%q\n' "$model"
    printf 'export JINA_RESTART_EFFORT=%q\n' "$effort"
    printf 'export JINA_RESTART_CONTEXT_TOKENS=%q\n' "$context_tokens"
    printf 'export JINA_RESTART_COMPACT_TOKENS=%q\n' "$compact_tokens"
    printf 'export JINA_RESTART_AGENT_WORKERS=%q\n' "$agent_workers"
    printf 'export JINA_RESTART_AUDIT_WORKERS=%q\n' "$audit_workers"
    printf 'export JINA_RESTART_LOG_RETENTION=%q\n' "$log_retention"
    printf 'export JINA_RESTART_GITHUB_TOKEN=%q\n' "$github_token"
  } >"$restart_file"
  chmod 600 "$environment_file" "$restart_file"
  echo "Recreated private local process state for retained PostgreSQL and artifact checkpoints."
  echo "Static local API credentials were rotated; repository data and Board state were not changed."
}

capture_current_restart_state() {
  local state_directory="$1" restart_file="$2"
  local environment_file="${JINA_DEV_ENV_FILE:-/tmp/jina-dev.env}"
  local container="${JINA_DEV_CONTAINER:-jina-dev-postgres}"
  if [[ -e "$restart_file" ]]; then
    echo "Refusing to overwrite existing restart state: $restart_file" >&2
    return 1
  fi
  if [[ "$container" != "jina-dev-postgres" ]]; then
    echo "--capture-current supports only the fixed local container jina-dev-postgres" >&2
    return 1
  fi
  assert_private_owned_file "$environment_file"
  # Generated by dev-up with mode 600 and shell-escaped values.
  # shellcheck disable=SC1090
  source "$environment_file"
  restart_required \
    JINA_API_URL JINA_INTERNAL_TOKEN JINA_CONTEXT_TOKEN JINA_TENANT_ID \
    JINA_DEV_STATE_DIR CONTEXT_ARTIFACT_DIRECTORY PAGEINDEX_SOURCE_ROOT \
    CONTEXT_PAGEINDEX_PYTHON CONTEXT_PAGEINDEX_WORKER
  # shellcheck disable=SC2031 # Values were sourced in this function, not from the API subprocess.
  local captured_tenant="$JINA_TENANT_ID"
  # shellcheck disable=SC2031 # Values were sourced in this function, not from the API subprocess.
  local captured_artifacts="$CONTEXT_ARTIFACT_DIRECTORY"
  [[ "$JINA_DEV_STATE_DIR" == "$state_directory" ]] || {
    echo "Environment state directory does not match $state_directory" >&2
    return 1
  }
  [[ "$JINA_API_URL" == "http://127.0.0.1:4180" ]] || {
    echo "--capture-current supports only the fixed local API port 4180" >&2
    return 1
  }
  [[ -d "$captured_artifacts" ]] || {
    echo "Captured immutable artifact directory is missing" >&2
    return 1
  }

  local owner running
  owner="$(docker inspect -f '{{ index .Config.Labels "com.jina.local-context.repo" }}' \
    "$container" 2>/dev/null || true)"
  running="$(docker inspect -f '{{.State.Running}}' "$container" 2>/dev/null || true)"
  [[ "$owner" == "$REPO" && "$running" == "true" ]] || {
    echo "The fixed PostgreSQL container is not running or does not belong to this checkout." >&2
    return 1
  }

  local -a roles=(snapshot agent-1 agent-2 agent-3 auditor-1 auditor-2 certification publication pageindex)
  local -a topics=(
    "run-context-input-snapshot"
    "run-context-page-plan|run-context-page-build"
    "run-context-page-plan|run-context-page-build"
    "run-context-page-plan|run-context-page-build"
    "run-context-page-build"
    "run-context-page-build"
    "run-context-page-plan"
    "run-context-publication"
    "run-context-publication"
  )
  local -a pid_files=("$state_directory"/worker-*.pid)
  [[ ${#pid_files[@]} -eq ${#roles[@]} ]] || {
    echo "Recorded worker topology is not the fixed 3-agent/2-auditor Board topology." >&2
    return 1
  }

  local api_pid
  api_pid="$(owned_recorded_pid "$state_directory/api.pid" api)"
  local fixed_database_url="postgres://jina_runtime:dev-runtime@127.0.0.1:55480/jina_dev"
  local fixed_migration_database_url="postgres://jina_app:dev-migration@127.0.0.1:55480/jina_dev"
  [[ "$(captured_process_value "$api_pid" DATABASE_URL)" == "$fixed_database_url" ]] || {
    echo "Running API does not use the fixed local runtime database." >&2
    return 1
  }
  [[ "$(captured_process_value "$api_pid" INTERNAL_API_TOKEN)" == "$JINA_INTERNAL_TOKEN" ]] || {
    echo "Environment internal token does not match the owned API process." >&2
    return 1
  }
  [[ "$(captured_process_value "$api_pid" CONTEXT_API_TOKEN)" == "$JINA_CONTEXT_TOKEN" ]] || {
    echo "Environment context token does not match the owned API process." >&2
    return 1
  }
  [[ "$(captured_process_value "$api_pid" JINA_TENANT_ID)" == "$captured_tenant" ]] || {
    echo "Environment tenant does not match the owned API process." >&2
    return 1
  }
  local captured_query_principal
  captured_query_principal="$(
    jina_resolve_local_context_query_principal \
      "$captured_tenant" \
      "$(captured_process_value "$api_pid" JINA_CONTEXT_PRINCIPAL_ID)" \
      "running API JINA_CONTEXT_PRINCIPAL_ID"
  )"
  [[ "$(captured_process_value "$api_pid" JINA_TENANT_ADMIN_PRINCIPALS)" == "tenant:$captured_tenant" ]] || {
    echo "Running API does not keep the tenant principal as the sole local tenant administrator." >&2
    return 1
  }
  [[ "$(captured_process_value "$api_pid" CONTEXT_ARTIFACT_DIRECTORY)" == "$captured_artifacts" ]] || {
    echo "Environment artifact directory does not match the owned API process." >&2
    return 1
  }

  local role pid expected_port
  local index
  for index in "${!roles[@]}"; do
    role="${roles[$index]}"
    pid="$(owned_recorded_pid "$state_directory/worker-$role.pid" "worker-$role")"
    expected_port=$((8091 + index))
    [[ "$(captured_process_value "$pid" WORKER_ID)" == "dev-$role" ]] || {
      echo "Worker $role id does not match the fixed topology." >&2
      return 1
    }
    [[ "$(captured_process_value "$pid" WORKER_TOPICS)" == "${topics[$index]}" ]] || {
      echo "Worker $role topics do not match the fixed topology." >&2
      return 1
    }
    [[ "$(captured_process_value "$pid" PORT)" == "$expected_port" ]] || {
      echo "Worker $role port does not match the fixed topology." >&2
      return 1
    }
    [[ "$(captured_process_value "$pid" INTERNAL_API_TOKEN)" == "$JINA_INTERNAL_TOKEN" ]] || {
      echo "Worker $role token does not match the owned API." >&2
      return 1
    }
  done

  local agent_pid
  agent_pid="$(<"$state_directory/worker-agent-1.pid")"
  local model effort codex_home codex_binary github_token
  local pageindex_source pageindex_python pageindex_worker
  model="$(captured_process_value "$agent_pid" CONTEXT_CODEX_MODEL)"
  effort="$(captured_process_value "$agent_pid" CONTEXT_CODEX_EFFORT)"
  codex_home="$(captured_process_value "$agent_pid" CODEX_HOME)"
  codex_binary="$(captured_process_value "$agent_pid" CODEX_BINARY)"
  github_token="$(captured_process_value "$agent_pid" GITHUB_API_TOKEN)"
  pageindex_source="$(captured_process_value "$agent_pid" PAGEINDEX_SOURCE_ROOT)"
  pageindex_python="$(captured_process_value "$agent_pid" CONTEXT_PAGEINDEX_PYTHON)"
  pageindex_worker="$(captured_process_value "$agent_pid" CONTEXT_PAGEINDEX_WORKER)"
  restart_required model effort codex_home codex_binary pageindex_source pageindex_python pageindex_worker
  [[ "$pageindex_source" == "$PAGEINDEX_SOURCE_ROOT" &&
    "$pageindex_python" == "$CONTEXT_PAGEINDEX_PYTHON" &&
    "$pageindex_worker" == "$CONTEXT_PAGEINDEX_WORKER" ]] || {
    echo "PageIndex settings differ between the environment and owned workers." >&2
    return 1
  }
  [[ -x "$codex_binary" && -f "$codex_home/auth.json" ]] || {
    echo "Captured Codex binary/session is unavailable." >&2
    return 1
  }
  PAGEINDEX_SOURCE_ROOT="$pageindex_source" "$pageindex_python" "$pageindex_worker" --probe >/dev/null

  umask 077
  {
    printf 'export JINA_RESTART_REPO=%q\n' "$REPO"
    printf 'export JINA_RESTART_CONTAINER=%q\n' "$container"
    printf 'export JINA_RESTART_ENV_FILE=%q\n' "$environment_file"
    printf 'export JINA_RESTART_DATABASE_URL=%q\n' "$fixed_database_url"
    printf 'export JINA_RESTART_MIGRATION_DATABASE_URL=%q\n' "$fixed_migration_database_url"
    printf 'export JINA_RESTART_RUNTIME_DB_USER=%q\n' jina_runtime
    printf 'export JINA_RESTART_API_PORT=%q\n' 4180
    printf 'export JINA_RESTART_WORKER_PORT_BASE=%q\n' 8091
    printf 'export JINA_RESTART_PGPORT=%q\n' 55480
    printf 'export JINA_RESTART_TENANT=%q\n' "$captured_tenant"
    printf 'export JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID=%q\n' "$captured_query_principal"
    printf 'export JINA_RESTART_INTERNAL_TOKEN=%q\n' "$JINA_INTERNAL_TOKEN"
    printf 'export JINA_RESTART_CONTEXT_TOKEN=%q\n' "$JINA_CONTEXT_TOKEN"
    printf 'export JINA_RESTART_ARTIFACT_DIR=%q\n' "$captured_artifacts"
    printf 'export JINA_RESTART_PAGEINDEX_SOURCE_ROOT=%q\n' "$pageindex_source"
    printf 'export JINA_RESTART_PAGEINDEX_PYTHON=%q\n' "$pageindex_python"
    printf 'export JINA_RESTART_PAGEINDEX_WORKER=%q\n' "$pageindex_worker"
    printf 'export JINA_RESTART_CODEX_HOME=%q\n' "$codex_home"
    printf 'export JINA_RESTART_CODEX_BINARY=%q\n' "$codex_binary"
    printf 'export JINA_RESTART_MODEL=%q\n' "$model"
    printf 'export JINA_RESTART_EFFORT=%q\n' "$effort"
    printf 'export JINA_RESTART_CONTEXT_TOKENS=%q\n' 128000
    printf 'export JINA_RESTART_COMPACT_TOKENS=%q\n' 96000
    printf 'export JINA_RESTART_AGENT_WORKERS=%q\n' 3
    printf 'export JINA_RESTART_AUDIT_WORKERS=%q\n' 2
    printf 'export JINA_RESTART_LOG_RETENTION=%q\n' 5
    printf 'export JINA_RESTART_GITHUB_TOKEN=%q\n' "$github_token"
  } >"$restart_file"
  chmod 600 "$restart_file"
  echo "Captured validated process settings in $restart_file."
  echo "No process, container, Board state, artifact, token, environment, or log was changed."
  echo "Run scripts/dev-restart.sh to perform the process-only restart."
}

assert_private_owned_file() {
  python3 - "$1" <<'PY'
import os
import stat
import sys

path = sys.argv[1]
metadata = os.lstat(path)
if not stat.S_ISREG(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
    raise SystemExit("file must be a regular non-symlink")
if metadata.st_uid != os.getuid():
    raise SystemExit("file must be owned by the current user")
if metadata.st_mode & 0o077:
    raise SystemExit("file permissions must be 0600 or stricter")
PY
}

owned_recorded_pid() {
  local pid_file="$1" label="$2" pid="" expected command
  [[ -f "$pid_file" && ! -L "$pid_file" ]] || {
    echo "Missing trusted pid file: $pid_file" >&2
    return 1
  }
  read -r pid <"$pid_file"
  [[ "$pid" =~ ^[1-9][0-9]*$ ]] || {
    echo "Invalid pid in $pid_file" >&2
    return 1
  }
  expected="$(jina_expected_process_path "$REPO" "$label")"
  command="$(jina_process_command "$pid")"
  [[ "$command" == *"$expected"* ]] || {
    echo "PID $pid in $pid_file is not owned by this checkout." >&2
    return 1
  }
  printf '%s\n' "$pid"
}

captured_process_value() {
  local pid="$1" name="$2"
  PID_TO_CAPTURE="$pid" NAME_TO_CAPTURE="$name" python3 - <<'PY'
import os
import re
import subprocess

pid = os.environ["PID_TO_CAPTURE"]
name = os.environ["NAME_TO_CAPTURE"]
proc = f"/proc/{pid}/environ"
if os.path.isfile(proc):
    values = open(proc, "rb").read().split(b"\0")
    prefix = name.encode() + b"="
    matches = [value[len(prefix):].decode() for value in values if value.startswith(prefix)]
else:
    output = subprocess.check_output(["ps", "eww", "-p", pid, "-o", "command="], text=True)
    match = re.search(r"(?:^|\s)" + re.escape(name) + r"=([^\s]*)", output)
    matches = [match.group(1)] if match else []
if len(matches) != 1:
    raise SystemExit(f"owned process {pid} does not expose exactly one {name}")
print(matches[0], end="")
PY
}

restart_required() {
  local name
  for name in "$@"; do
    if [[ -z "${!name:-}" ]]; then
      echo "Restart state is missing $name; run scripts/dev-up.sh again." >&2
      return 1
    fi
  done
}

resolve_migration_restart_metadata() {
  if [[ -n "${JINA_RESTART_MIGRATION_DATABASE_URL:-}" &&
    -n "${JINA_RESTART_RUNTIME_DB_USER:-}" ]]; then
    return 0
  fi
  # Restart files created before migration metadata was persisted can still
  # upgrade the one fixed default local stack. Never guess credentials for a
  # customized database; a fresh dev-up/capture must record those explicitly.
  if [[ "${JINA_RESTART_DATABASE_URL:-}" == \
    "postgres://jina_runtime:dev-runtime@127.0.0.1:55480/jina_dev" ]]; then
    JINA_RESTART_MIGRATION_DATABASE_URL="postgres://jina_app:dev-migration@127.0.0.1:55480/jina_dev"
    JINA_RESTART_RUNTIME_DB_USER="jina_runtime"
    return 0
  fi
  echo "Restart state predates retained migration metadata; run scripts/dev-up.sh again." >&2
  return 1
}

resolve_context_query_principal_restart_metadata() {
  JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID="$(
    jina_resolve_local_context_query_principal \
      "$JINA_RESTART_TENANT" \
      "${JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID:-}" \
      JINA_RESTART_CONTEXT_QUERY_PRINCIPAL_ID
  )"
}

update_shell_export_file() {
  local file="$1" variable="$2" value="$3" temporary replacement
  [[ "$variable" =~ ^[A-Z][A-Z0-9_]*$ ]] || {
    echo "Refusing invalid local environment variable name: $variable" >&2
    return 2
  }
  [[ "$value" =~ ^(tenant:[0-9a-f-]{36}|user:[^[:space:]@]+@[^[:space:]@]+)$ ]] || {
    echo "Refusing invalid local Context principal value." >&2
    return 2
  }
  temporary="$(mktemp "$file.query-principal.XXXXXX")"
  replacement="export $variable=$value"
  if ! awk -v prefix="export $variable=" -v replacement="$replacement" '
    index($0, prefix) == 1 {
      if (!replaced) {
        print replacement
        replaced = 1
      }
      next
    }
    { print }
    END {
      if (!replaced) print replacement
    }
  ' "$file" >"$temporary"; then
    rm -f -- "$temporary"
    return 1
  fi
  chmod 600 "$temporary"
  mv "$temporary" "$file"
}

assert_retained_database_targets() {
  RUNTIME_DATABASE_URL="$1" \
    MIGRATION_DATABASE_URL="$2" \
    EXPECTED_PGPORT="$3" \
    EXPECTED_RUNTIME_USER="$4" \
    python3 - <<'PY'
import os
import urllib.parse

runtime = urllib.parse.urlsplit(os.environ["RUNTIME_DATABASE_URL"])
migration = urllib.parse.urlsplit(os.environ["MIGRATION_DATABASE_URL"])
expected_port = int(os.environ["EXPECTED_PGPORT"])
expected_runtime_user = os.environ["EXPECTED_RUNTIME_USER"]

def scope(label, parsed):
    if parsed.scheme not in {"postgres", "postgresql"}:
        raise SystemExit(f"{label} connection is not PostgreSQL")
    if parsed.hostname not in {"127.0.0.1", "localhost"}:
        raise SystemExit(f"{label} connection does not target retained local PostgreSQL")
    if parsed.port != expected_port:
        raise SystemExit(f"{label} connection does not use the retained PostgreSQL port")
    database = parsed.path.removeprefix("/")
    if not database or "/" in database:
        raise SystemExit(f"{label} connection has an invalid database name")
    if not parsed.username or parsed.password is None:
        raise SystemExit(f"{label} connection lacks private login credentials")
    return parsed.port, database

runtime_scope = scope("runtime", runtime)
migration_scope = scope("migration", migration)
if runtime_scope != migration_scope:
    raise SystemExit("runtime and migration connections do not target the same retained PostgreSQL database")
if runtime.username != expected_runtime_user:
    raise SystemExit("runtime connection login does not match retained runtime role metadata")
if migration.username == runtime.username:
    raise SystemExit("migration connection must use a distinct non-runtime login")
PY
}

file_digest() {
  cksum <"$1"
}

context_builds_json() {
  curl -fsS "http://127.0.0.1:$JINA_RESTART_API_PORT/wiki/builds" \
    -H "authorization: Bearer $JINA_RESTART_INTERNAL_TOKEN" \
    -H "x-jina-tenant-id: $JINA_RESTART_TENANT" \
    -H "x-jina-principal-id: tenant:$JINA_RESTART_TENANT"
}

verify_worker_topology() {
  local url="$1" expected_id="$2" expected_topics="$3" payload
  payload="$(curl -fsS "$url")"
  EXPECTED_WORKER_ID="$expected_id" EXPECTED_TOPICS="$expected_topics" HEALTH_PAYLOAD="$payload" \
    node -e '
const health = JSON.parse(process.env.HEALTH_PAYLOAD);
const expected = process.env.EXPECTED_TOPICS.split("|");
if (health.ok !== true) throw new Error("worker is not healthy");
if (health.workerId !== process.env.EXPECTED_WORKER_ID) throw new Error("worker id mismatch");
if (JSON.stringify(health.topics) !== JSON.stringify(expected)) throw new Error("worker topics mismatch");
'
}

assert_builds_preserved() {
  local before="$1" after="$2"
  [[ -z "$before" ]] && return 0
  # shellcheck disable=SC2016 # `${build.id}` belongs to the JavaScript program.
  BEFORE_BUILDS="$before" AFTER_BUILDS="$after" node -e '
const before = JSON.parse(process.env.BEFORE_BUILDS).builds ?? [];
const after = new Map((JSON.parse(process.env.AFTER_BUILDS).builds ?? []).map(build => [build.id, build]));
for (const build of before.filter(build => build.status !== "completed")) {
  if (!after.has(build.id)) throw new Error(`in-flight/failed build disappeared across restart: ${build.id}`);
}
'
}

print_build_observability() {
  local builds="$1" api_port="$2" observations
  observations="$(BUILDS_PAYLOAD="$builds" node -e '
const builds = JSON.parse(process.env.BUILDS_PAYLOAD).builds ?? [];
for (const build of builds.filter(build => build.status === "active" || build.status === "failed").slice(0, 10)) {
  console.log([build.id, build.status, build.repository, build.ref].join("\t"));
}
')"
  if [[ -z "$observations" ]]; then
    echo "No active or failed build exists; the persisted Board catalog is reachable."
    return 0
  fi
  echo "Observable resumable/diagnostic builds:"
  while IFS=$'\t' read -r build_id status repository ref; do
    local progress
    progress="$(curl -fsS \
      "http://127.0.0.1:$api_port/wiki/builds/$(urlencode "$build_id")/progress" \
      -H "authorization: Bearer $JINA_RESTART_INTERNAL_TOKEN" \
      -H "x-jina-tenant-id: $JINA_RESTART_TENANT" \
      -H "x-jina-principal-id: tenant:$JINA_RESTART_TENANT")"
    BUILD_PROGRESS="$progress" node -e 'JSON.parse(process.env.BUILD_PROGRESS)'
    echo "  $build_id  $status  $repository@$ref"
    echo "    source $JINA_RESTART_ENV_FILE"
    echo "    scripts/context-build.sh --watch $build_id"
  done <<<"$observations"
}

urlencode() {
  node -e 'process.stdout.write(encodeURIComponent(process.argv[1]))' "$1"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  dev_restart_main "$@"
fi
